name: oracle
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  audioplayers: ^5.2.0
  awesome_notifications: ^0.10.1
  firebase_data_connect: ^0.1.0
  flutter_cache_manager: ^3.3.1
  flutter_map_cache: ^1.0.0
  shared_preferences: ^2.2.2
  lottie: ^3.3.0
  logging: ^1.2.0
  http: ^1.1.0
  flutter_map: ^8.0.0
  mapbox_maps_flutter: ^2.6.0
  latlong2: ^0.9.0
  firebase_core: ^3.12.0
  firebase_auth: ^5.4.1
  firebase_storage: ^12.4.1
  cloud_firestore: ^5.6.2
  fl_chart: ^0.70.2
  image_picker: ^1.1.2
  provider: ^6.0.5
  firebase_database: ^11.3.3
  firebase_app_check: ^0.3.2+1
  path_provider: ^2.1.5
  screenshot: ^3.0.0
  pdf: ^3.8.4
  share_plus: ^10.1.4
  firebase_messaging: ^15.2.3
  connectivity_plus: ^6.1.3
  device_info_plus: ^9.1.0
  package_info_plus: ^4.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/applogo.png
    - assets/animations/oracle_wisdom.json
    - assets/animations/splash_screen1.json
    - assets/audio/
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/applogo.png"  # Create this image file or use your own
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/applogo.png"
